[versions]
agp = "8.4.1"
kotlin = "2.0.0"
accompanistSystemuicontroller = "0.34.0"
activityCompose = "1.9.0"
libphonenumber = "8.13.37"
material3 = "1.2.1"
composeCompiler = "1.5.14"
ktx = "1.13.1"
spotless = "6.25.0"
kotlin-compatibility = "0.14.0"
dokka = "1.9.20"
gradleMavenPublish = "0.28.0"
nmcp = "0.0.7"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-compatibility" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublish" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }